In [598]:
import os
import shutil
from pathlib import Path

# Extracting data for raw layer

In [600]:
downloads_path = str(Path.home() / "Downloads")
notebook_dir = os.getcwd()  
raw_folder = os.path.join(notebook_dir, "raw_folder")  

os.makedirs(raw_folder, exist_ok=True)

files = os.listdir(downloads_path)

for file in files:
    if file.startswith("majorProject"):
        shutil.copy(os.path.join(downloads_path, file), raw_folder)

print(f"CSV files have been copied to {raw_folder}")

CSV files have been copied to C:\Users\PurnimaKabadwal\Desktop\DE_MAJOR_pROJECT\raw_folder

# Starting Preparation Layer

In [602]:
import pandas as pd

df_engagements = pd.read_csv('./raw_folder/majorProject.engagements.csv')
df_feedbacks = pd.read_csv('./raw_folder/majorProject.feedbacks.csv')
df_learningmaterial = pd.read_csv('./raw_folder/majorProject.learningmaterials.csv')
df_modules = pd.read_csv('./raw_folder/majorProject.modules.csv')
df_quizzes = pd.read_csv('./raw_folder/majorProject.quizzes.csv')
df_userss = pd.read_csv('./raw_folder/majorProject.userss.csv')

In [603]:
df_engagements

,_id,userId,learningMaterialCompletion[0].learningMaterialId,learningMaterialCompletion[0].completed,learningMaterialCompletion[0]._id,quizScore,moduleCompletion[0].moduleId,moduleCompletion[1].moduleId,moduleCompletion[2].moduleId,moduleCompletion[3].moduleId,...,moduleCompletion[5].completed,moduleCompletion[6].completed,moduleCompletion[0]._id,moduleCompletion[1]._id,moduleCompletion[2]._id,moduleCompletion[3]._id,moduleCompletion[4]._id,moduleCompletion[5]._id,moduleCompletion[6]._id,__v
0,670382462c5b86945273f2e7,670382422c5b86945273d278,670382432c5b86945273d6e3,True,670382462c5b86945273f2e8,31,670382442c5b86945273db12,NaN,NaN,NaN,...,NaN,NaN,670382462c5b86945273f2e9,NaN,NaN,NaN,NaN,NaN,NaN,0
1,670382462c5b86945273f2ea,670382422c5b86945273d353,670382432c5b86945273d4ac,True,670382462c5b86945273f2eb,89,670382442c5b86945273d7be,670382442c5b86945273d8ab,NaN,NaN,...,NaN,NaN,670382462c5b86945273f2ec,670382462c5b86945273f2ed,NaN,NaN,NaN,NaN,NaN,0
2,670382462c5b86945273f2ee,670382422c5b86945273d37f,670382432c5b86945273d51d,True,670382462c5b86945273f2ef,28,670382442c5b86945273d81e,670382442c5b86945273d8cd,NaN,NaN,...,NaN,NaN,670382462c5b86945273f2f0,670382462c5b86945273f2f1,NaN,NaN,NaN,NaN,NaN,0
3,670382462c5b86945273f2f2,670382422c5b86945273d25f,670382432c5b86945273d632,True,670382462c5b86945273f2f3,65,670382442c5b86945273db3f,NaN,NaN,NaN,...,NaN,NaN,670382462c5b86945273f2f4,NaN,NaN,NaN,NaN,NaN,NaN,0
4,670382462c5b86945273f2f5,670382422c5b86945273d344,670382432c5b86945273d609,True,670382462c5b86945273f2f6,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,670382462c5b86945273fe88,670382422c5b86945273d053,670382432c5b86945273d3a8,True,670382462c5b86945273fe89,22,670382442c5b86945273db14,NaN,NaN,NaN,...,NaN,NaN,670382462c5b86945273fe8a,NaN,NaN,NaN,NaN,NaN,NaN,0
996,670382462c5b86945273fe8b,670382422c5b86945273d041,670382432c5b86945273d6f8,True,670382462c5b86945273fe8c,40,670382442c5b86945273d854,670382442c5b86945273dafe,NaN,NaN,...,NaN,NaN,670382462c5b86945273fe8d,670382462c5b86945273fe8e,NaN,NaN,NaN,NaN,NaN,0
997,670382462c5b86945273fe8f,670382422c5b86945273d087,670382432c5b86945273d635,True,670382462c5b86945273fe90,99,670382442c5b86945273db2b,NaN,NaN,NaN,...,NaN,NaN,670382462c5b86945273fe91,NaN,NaN,NaN,NaN,NaN,NaN,0
998,670382462c5b86945273fe92,670382422c5b86945273cfc8,670382432c5b86945273d512,True,670382462c5b86945273fe93,32,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
999,670382462c5b86945273fe94,670382422c5b86945273d157,670382432c5b86945273d57e,True,670382462c5b86945273fe95,79,670382442c5b86945273d793,NaN,NaN,NaN,...,NaN,NaN,670382462c5b86945273fe96,NaN,NaN,NaN,NaN,NaN,NaN,0

# Mostly data is cleaned except engagements table

In [605]:
selected_engagements_columns = ['_id', 'userId','learningMaterialCompletion[0].learningMaterialId','quizScore']
df_selected_engagements = df_engagements[selected_engagements_columns]

In [606]:
df_selected_engagements

,_id,userId,learningMaterialCompletion[0].learningMaterialId,quizScore
0,670382462c5b86945273f2e7,670382422c5b86945273d278,670382432c5b86945273d6e3,31
1,670382462c5b86945273f2ea,670382422c5b86945273d353,670382432c5b86945273d4ac,89
2,670382462c5b86945273f2ee,670382422c5b86945273d37f,670382432c5b86945273d51d,28
3,670382462c5b86945273f2f2,670382422c5b86945273d25f,670382432c5b86945273d632,65
4,670382462c5b86945273f2f5,670382422c5b86945273d344,670382432c5b86945273d609,0
...,...,...,...,...
995,670382462c5b86945273fe88,670382422c5b86945273d053,670382432c5b86945273d3a8,22
996,670382462c5b86945273fe8b,670382422c5b86945273d041,670382432c5b86945273d6f8,40
997,670382462c5b86945273fe8f,670382422c5b86945273d087,670382432c5b86945273d635,99
998,670382462c5b86945273fe92,670382422c5b86945273cfc8,670382432c5b86945273d512,32
999,670382462c5b86945273fe94,670382422c5b86945273d157,670382432c5b86945273d57e,79

In [607]:
df_selected_engagements = df_selected_engagements.rename(columns={
    'learningMaterialCompletion[0].learningMaterialId': 'learningMaterialId'  
})
df_selected_engagements

,_id,userId,learningMaterialId,quizScore
0,670382462c5b86945273f2e7,670382422c5b86945273d278,670382432c5b86945273d6e3,31
1,670382462c5b86945273f2ea,670382422c5b86945273d353,670382432c5b86945273d4ac,89
2,670382462c5b86945273f2ee,670382422c5b86945273d37f,670382432c5b86945273d51d,28
3,670382462c5b86945273f2f2,670382422c5b86945273d25f,670382432c5b86945273d632,65
4,670382462c5b86945273f2f5,670382422c5b86945273d344,670382432c5b86945273d609,0
...,...,...,...,...
995,670382462c5b86945273fe88,670382422c5b86945273d053,670382432c5b86945273d3a8,22
996,670382462c5b86945273fe8b,670382422c5b86945273d041,670382432c5b86945273d6f8,40
997,670382462c5b86945273fe8f,670382422c5b86945273d087,670382432c5b86945273d635,99
998,670382462c5b86945273fe92,670382422c5b86945273cfc8,670382432c5b86945273d512,32
999,670382462c5b86945273fe94,670382422c5b86945273d157,670382432c5b86945273d57e,79

In [608]:
selected_quizzes_columns = ['_id','title','learningMaterialId']
df_selected_quizzes =  df_quizzes[selected_quizzes_columns]

In [609]:
df_selected_quizzes

,_id,title,learningMaterialId
0,670382442c5b86945273db70,Rustic Granite Towels,670382432c5b86945273d59f
1,670382442c5b86945273db75,Refined Frozen Shirt,670382432c5b86945273d4cc
2,670382442c5b86945273db7a,Rustic Frozen Shoes,670382432c5b86945273d545
3,670382442c5b86945273db7f,Sleek Cotton Towels,670382432c5b86945273d5d2
4,670382442c5b86945273db84,Licensed Cotton Pants,670382432c5b86945273d465
...,...,...,...
995,670382442c5b86945273eedf,Refined Wooden Keyboard,670382432c5b86945273d5e0
996,670382442c5b86945273eee4,Electronic Cotton Table,670382432c5b86945273d62c
997,670382442c5b86945273eee9,Tasty Wooden Towels,670382432c5b86945273d693
998,670382442c5b86945273eeee,Modern Rubber Salad,670382432c5b86945273d583
999,670382442c5b86945273eef3,Handmade Rubber Mouse,670382432c5b86945273d5d4

In [610]:
dataframes = {
    "prep_engagements.csv":df_selected_engagements ,
    "prep_quizzes.csv": df_selected_quizzes,
    "prep_feedbacks.csv": df_feedbacks,
    "prep_modules.csv" : df_modules,
    "prep_learningmaterials.csv" :df_learningmaterial,
    "prep_users.csv" :df_userss
}

prep_folder = "prep_folders"

if not os.path.exists(prep_folder):
    os.makedirs(prep_folder)

for filename, df in dataframes.items():
    file_path = os.path.join(prep_folder, filename)
    df.to_csv(file_path, index=False) 
print(f"All DataFrames have been saved in the '{prep_folder}' folder.")

All DataFrames have been saved in the 'prep_folders' folder.

In [611]:
df_selected_engagements

,_id,userId,learningMaterialId,quizScore
0,670382462c5b86945273f2e7,670382422c5b86945273d278,670382432c5b86945273d6e3,31
1,670382462c5b86945273f2ea,670382422c5b86945273d353,670382432c5b86945273d4ac,89
2,670382462c5b86945273f2ee,670382422c5b86945273d37f,670382432c5b86945273d51d,28
3,670382462c5b86945273f2f2,670382422c5b86945273d25f,670382432c5b86945273d632,65
4,670382462c5b86945273f2f5,670382422c5b86945273d344,670382432c5b86945273d609,0
...,...,...,...,...
995,670382462c5b86945273fe88,670382422c5b86945273d053,670382432c5b86945273d3a8,22
996,670382462c5b86945273fe8b,670382422c5b86945273d041,670382432c5b86945273d6f8,40
997,670382462c5b86945273fe8f,670382422c5b86945273d087,670382432c5b86945273d635,99
998,670382462c5b86945273fe92,670382422c5b86945273cfc8,670382432c5b86945273d512,32
999,670382462c5b86945273fe94,670382422c5b86945273d157,670382432c5b86945273d57e,79

# Reporting Tables

In [613]:
def get_top_employees(df_selected_engagements, df_userss):
 
    top_employees = df_selected_engagements.groupby('userId').agg(totalScore=('quizScore', 'sum')).reset_index()
    
    top_employees = top_employees.sort_values(by='totalScore', ascending=False).head(10)
    
    top_employees = top_employees.merge(
        df_userss[['firstName', 'lastName', 'department', '_id']], 
        left_on='userId', 
        right_on='_id', 
        suffixes=('', '_user')
    )
    
    top_employees = top_employees[['userId', 'firstName', 'lastName', 'department', 'totalScore']]
    
    return top_employees

def get_department_scores(df_selected_engagements, df_users):
    merged_df = df_selected_engagements.merge(df_userss, left_on='userId', right_on='_id', suffixes=('', '_user'))
    
    department_scores = merged_df.groupby('department').agg(
        averageScore=('quizScore', 'mean'),
        totalScore=('quizScore', 'sum'),
        count=('quizScore', 'size')
    ).reset_index()
    
    return department_scores
    


    
def get_top_feedback_learning_material(df_feedbacks, df_learningmaterial):
    top_material_feedbacks = df_feedbacks.groupby('learningMaterialId').agg(
        totalFeedbacks=('rating', 'count'),
        averageRating=('rating', 'mean')
    ).reset_index()
    
    top_material_feedbacks = top_material_feedbacks.sort_values(by='totalFeedbacks', ascending=False).head(1)
    
    top_material_feedbacks = top_material_feedbacks.merge(
        df_learningmaterial[['title', '_id']],
        left_on='learningMaterialId',
        right_on='_id',
        suffixes=('', '_material')
    )
    
    top_material_feedbacks = top_material_feedbacks[['learningMaterialId', 'title', 'totalFeedbacks', 'averageRating']]
    
    return top_material_feedbacks


top_employees = get_top_employees(df_selected_engagements,df_userss)
department_scores = get_department_scores(df_selected_engagements, df_userss)
top_learning_material = get_top_feedback_learning_material(df_feedbacks, df_learningmaterial)

print("Top Employees:\n", top_employees)
print("\nDepartment Scores:\n", department_scores)
print("\nTop Learning Material:\n", top_learning_material)


Reprtingdataframes = {
    "top_employees.csv":top_employees ,
    "department_scores.csv": department_scores,
    "top_learning_material.csv": top_learning_material,
}

Reporting = "Reporting"

if not os.path.exists(Reporting):
    os.makedirs(Reporting)

for filename, df in Reprtingdataframes.items():
    file_path = os.path.join(Reporting , filename)
    df.to_csv(file_path, index=False) 
print(f"All DataFrames have been saved in the '{Reporting }' folder.")

Top Employees:
                      userId   firstName     lastName        department  \
0  670382422c5b86945273d23c        Nick       Willms  Data Engineering
1  670382422c5b86945273d2c5   Andreanne        Koepp      Data Science
2  670382422c5b86945273d189       Wyatt      Padberg  Data Engineering
3  670382422c5b86945273d265   Nathaniel     Champlin  Data Engineering
4  670382422c5b86945273cff0      Cassie       Muller  Data Engineering
5  670382422c5b86945273d1e6     Garrett      Treutel  Data Engineering
6  670382422c5b86945273d0c9      Aileen  Greenfelder      Data Science
7  670382422c5b86945273d01f  Alexandria       Spinka  Data Engineering
8  670382422c5b86945273d2ac       Reese       Zulauf      Data Science
9  670382422c5b86945273d0db     Florian       O'Hara  Data Engineering

   totalScore
0         325
1         311
2         294
3         293
4         289
5         286
6         286
7         282
8         265
9         259

Department Scores:
          department  averageScore  totalScore  count
0  Data Engineering     49.997409       19299    386
1      Data Science     49.542056       15903    321
2        Full Stack     46.624573       13661    293

Top Learning Material:
          learningMaterialId               title  totalFeedbacks  averageRating
0  670382432c5b86945273d3c3  Elegant Frozen Car               6            3.0
All DataFrames have been saved in the 'Reporting' folder.